### ISSUE TITLE
unauthorized access for `skopeo copy`

### ISSUE THREAD

**Issue by vbatts** [projectatomic/skopeo#325]
When on a fresh host that does not even have docker installed (and no `~/.docker/config.json`), the copy fails like so:
```bash
$ skopeo copy docker://busybox oci:oci/busybox
FATA[0000] Error initializing image from source docker://busybox:latest: unable to retrieve auth token: 401 unauthorized
```
Are credentials required even for this example?

**Comment by runcom** [comment]
That..... Shouldn't.... I'll look into this.

**Comment by runcom** [comment]
```
12:32:09 [~] cd projectatomic/skopeo
~/go/src/github.com/projectatomic/skopeo
12:32:14 [github.com/projectatomic/skopeo] ‹master*› ls -la $HOME/.docker
ls: cannot access '/home/amurdaca/.docker': No such file or directory
12:32:15 [github.com/projectatomic/skopeo] ‹master*› rpm -q docker                         2 ↵
package docker is not installed
12:32:17 [github.com/projectatomic/skopeo] ‹master*› mkdir oci                             1 ↵
mkdir: cannot create directory ‘oci’: File exists
12:32:21 [github.com/projectatomic/skopeo] ‹master*› rm -rf oci                            1 ↵
12:32:26 [github.com/projectatomic/skopeo] ‹master› mkdir oci
12:32:32 [github.com/projectatomic/skopeo] ‹master› ./skopeo copy docker://busybox oci:oci/busybox
Getting image source signatures
Copying blob sha256:7520415ce76232cdd62ecc345cea5ea44f5b6b144dc62351f2cd2b08382532a3
 495.12 KB / 661.73 KB [=========================================>-------------]
 661.73 KB / 661.73 KB [=======================================================]Copying config sha256:636fcf0bc8246e08d2df4771dc764d35ea50428b8dfaa904773b0707cb4f6303
 0 B / 575 B [-----------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
12:32:42 [github.com/projectatomic/skopeo] ‹master*› ./skopeo --debug copy docker://busybox oci:oci/busybox
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]  No signature storage configuration found for docker.io/library/busybox:latest
DEBU[0000] IsRunningImageAllowed for image docker:docker.io/library/busybox:latest
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
DEBU[0000] GET https://registry-1.docker.io/v2/
DEBU[0000] Ping https://registry-1.docker.io/v2/ err <nil>
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401
DEBU[0001] GET https://registry-1.docker.io/v2/library/busybox/manifests/latest
Getting image source signatures
DEBU[0002] Will convert manifest from MIME type application/vnd.docker.distribution.manifest.v2+json to application/vnd.oci.image.manifest.v1+json
Skipping fetch of repeat blob sha256:7520415ce76232cdd62ecc345cea5ea44f5b6b144dc62351f2cd2b08382532a3
DEBU[0002] Downloading /v2/library/busybox/blobs/sha256:00f017a8c2a6e1fe2ffd05c281f27d069d2a99323a8cd514dd35f228ba26d2ff
DEBU[0002] GET https://registry-1.docker.io/v2/library/busybox/blobs/sha256:00f017a8c2a6e1fe2ffd05c281f27d069d2a99323a8cd514dd35f228ba26d2ff
Copying config sha256:636fcf0bc8246e08d2df4771dc764d35ea50428b8dfaa904773b0707cb4f6303
DEBU[0003] No compression detected
 0 B / 575 B [-----------------------------------------------------------------]DEBU[0003] Using original blob without modification

Writing manifest to image destination
Storing signatures
```

@vbatts I'm probably missing something cause I can't reproduce with latest skopeo master

**Comment by vbatts** [comment]
wacky! I just spun up a fresh f25 vm to reproduce and couldn't either. :confused: 
```bash
sudo dnf update -y
sudo dnf install -y bzr hg golang git openssl-devel systemd-devel device-mapper-devel gpgme-devel libassuan-devel btrfs-progs-devel
export GOPATH=$HOME
export PATH=$HOME/bin:$PATH
go get github.com/cpuguy83/go-md2man
sudo mv ~/bin/go-md2man /usr/bin/
go get -d github.com/projectatomic/skopeo
cd $GOPATH/github.com/projectatomic/skopeo
make binary-local
sudo make install
cd ~
mkdir ~/oci
skopeo copy docker://busybox oci:oci/busybox
```
and the ouput is: 
```
Getting image source signatures
Copying blob sha256:7520415ce76232cdd62ecc345cea5ea44f5b6b144dc62351f2cd2b08382532a3
 207.23 KB / 661.73 KB [=================>-------------------------------------]
 661.73 KB / 661.73 KB [=======================================================]Copying config sha256:636fcf0bc8246e08d2df4771dc764d35ea50428b8dfaa904773b0707cb4f6303
 0 B / 575 B [-----------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
```

Sorry to bother. Not sure why the other host was unauthorized.

**Comment by sosiouxme** [comment]
FWIW I saw similar when I had a `~/.docker/config.json` with expired auth.

```
# atomic pull  docker.io/busybox
Failed: unable to retrieve auth token: 401 unauthorized
# atomic --debug pull  docker.io/busybox
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', ignore=False, image='docker.io/busybox', profile=False, reg_type=None, storage=None)
Failed: unexpected http code: 429, URL: https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Atomic/pull.py", line 48, in pull_image
    remote_image_obj = be.make_remote_image(self.args.image)
  File "/usr/lib/python3.5/site-packages/Atomic/backends/_docker.py", line 271, in make_remote_image
    img_obj.populate_remote_inspect_info()
  File "/usr/lib/python3.5/site-packages/Atomic/objects/image.py", line 157, in populate_remote_inspect_info
    remote_inspect_info = self.remote_inspect()
  File "/usr/lib/python3.5/site-packages/Atomic/objects/image.py", line 174, in remote_inspect
    inspect_info = ri.inspect()
  File "/usr/lib/python3.5/site-packages/Atomic/discovery.py", line 41, in inspect
    inspect_data = util.skopeo_inspect("docker://{}".format(self.fqdn), return_json=True)
  File "/usr/lib/python3.5/site-packages/Atomic/util.py", line 330, in skopeo_inspect
    raise ValueError(error)
ValueError: unexpected http code: 429, URL: https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 203, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.5/site-packages/Atomic/pull.py", line 56, in pull_image
    raise ValueError("Failed: {}".format(e))
ValueError: Failed: unexpected http code: 429, URL: https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 216, in <module>
    sys.exit(1)
SystemExit: 1
```

Problem went away when I deleted `~/.docker/config.json`. It might be nice to handle this better, but just noting it here in case anyone else winds up here via Google as I did :)
